using System.IO;

namespace FreeCamManager.Services;

internal static class EmbeddedManagerUpdater
{
    private const string PayloadBase64 =
        "cGFyYW0oCiAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeT0kdHJ1ZSldW2ludF0kT2xkUGlkLAogICAgW1BhcmFtZXRlcihNYW5kYXRvcnk9JHRydWUpXVtzdHJp" +
        "bmddJEN1cnJlbnRFeGUsCiAgICBbUGFyYW1ldGVyKE1hbmRhdG9yeT0kdHJ1ZSldW3N0cmluZ10kU3RhZ2VkU291cmNlUm9vdCwKICAgIFtQYXJhbWV0ZXIo" +
        "TWFuZGF0b3J5PSR0cnVlKV1bc3RyaW5nXSRUYXJnZXRWZXJzaW9uLAogICAgW3N3aXRjaF0kUmVzdGFydAopCgokRXJyb3JBY3Rpb25QcmVmZXJlbmNlID0g" +
        "J1N0b3AnClNldC1TdHJpY3RNb2RlIC1WZXJzaW9uIExhdGVzdAoKJEN1cnJlbnRFeGUgPSBbU3lzdGVtLklPLlBhdGhdOjpHZXRGdWxsUGF0aCgkQ3VycmVu" +
        "dEV4ZSkKJFN0YWdlZFNvdXJjZVJvb3QgPSBbU3lzdGVtLklPLlBhdGhdOjpHZXRGdWxsUGF0aCgkU3RhZ2VkU291cmNlUm9vdCkKJFN0YWdlRGlyID0gU3Bs" +
        "aXQtUGF0aCAtUGFyZW50ICRTdGFnZWRTb3VyY2VSb290CmlmICgoU3BsaXQtUGF0aCAtTGVhZiAkU3RhZ2VEaXIpIC1pZXEgJ3NvdXJjZScpIHsKICAgICRT" +
        "dGFnZURpciA9IFNwbGl0LVBhdGggLVBhcmVudCAkU3RhZ2VEaXIKfQokTG9nRmlsZSA9IEpvaW4tUGF0aCAkU3RhZ2VEaXIgJ1VQREFURV9SRVNVTFQudHh0" +
        "JwokU3RhdHVzRmlsZSA9IEpvaW4tUGF0aCAkU3RhZ2VEaXIgJ1VQREFURV9TVEFUVVMuanNvbicKJEJ1aWxkU2NyaXB0ID0gSm9pbi1QYXRoICRTdGFnZWRT" +
        "b3VyY2VSb290ICdzcmMtd3BmXEJ1aWxkX3YzX09uX1dpbmRvd3MucHMxJwokQnVpbGRPdXQgPSBKb2luLVBhdGggJFN0YWdlRGlyICdidWlsZC1vdXRwdXQn" +
        "CiROZXdFeGUgPSBKb2luLVBhdGggJEJ1aWxkT3V0ICdGcmVlQ2FtX01hbmFnZXIuZXhlJwokVGFyZ2V0RGlyID0gU3BsaXQtUGF0aCAtUGFyZW50ICRDdXJy" +
        "ZW50RXhlCiRUZW1wRXhlID0gJEN1cnJlbnRFeGUgKyAnLm5ldycKJEJhY2t1cEV4ZSA9ICRDdXJyZW50RXhlICsgJy5iYWsnCgpmdW5jdGlvbiBXcml0ZS1V" +
        "cGRhdGVMb2coW3N0cmluZ10kVGV4dCkgewogICAgJHN0YW1wID0gR2V0LURhdGUgLUZvcm1hdCAneXl5eS1NTS1kZCBISDptbTpzcycKICAgICRsaW5lID0g" +
        "Ilskc3RhbXBdICRUZXh0IgogICAgV3JpdGUtSG9zdCAkbGluZQogICAgQWRkLUNvbnRlbnQgLUxpdGVyYWxQYXRoICRMb2dGaWxlIC1WYWx1ZSAkbGluZSAt" +
        "RW5jb2RpbmcgVVRGOAp9CgpmdW5jdGlvbiBXcml0ZS1TdGF0dXMoW3N0cmluZ10kU3RhdGUsIFtzdHJpbmddJE1lc3NhZ2UpIHsKICAgICRwYXlsb2FkID0g" +
        "W29yZGVyZWRdQHsKICAgICAgICBzdGF0ZSA9ICRTdGF0ZQogICAgICAgIHRhcmdldFZlcnNpb24gPSAkVGFyZ2V0VmVyc2lvbgogICAgICAgIG1lc3NhZ2Ug" +
        "PSAkTWVzc2FnZQogICAgICAgIHVwZGF0ZWRBdCA9IChHZXQtRGF0ZSkuVG9TdHJpbmcoJ28nKQogICAgICAgIGxvZ0ZpbGUgPSAkTG9nRmlsZQogICAgfSB8" +
        "IENvbnZlcnRUby1Kc29uIC1EZXB0aCAzCiAgICBbU3lzdGVtLklPLkZpbGVdOjpXcml0ZUFsbFRleHQoJFN0YXR1c0ZpbGUsICRwYXlsb2FkLCAoTmV3LU9i" +
        "amVjdCBTeXN0ZW0uVGV4dC5VVEY4RW5jb2RpbmcoJGZhbHNlKSkpCn0KCmZ1bmN0aW9uIFJlc3RhcnQtTWFuYWdlcklmUmVxdWVzdGVkIHsKICAgIGlmICgk" +
        "UmVzdGFydCAtYW5kIChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRDdXJyZW50RXhlKSkgewogICAgICAgIHRyeSB7CiAgICAgICAgICAgIFdyaXRlLVVwZGF0" +
        "ZUxvZyAiUmVzdGFydGluZyBNYW5hZ2VyOiAkQ3VycmVudEV4ZSIKICAgICAgICAgICAgU3RhcnQtUHJvY2VzcyAtRmlsZVBhdGggJEN1cnJlbnRFeGUgLVdv" +
        "cmtpbmdEaXJlY3RvcnkgJFRhcmdldERpcgogICAgICAgIH0gY2F0Y2ggewogICAgICAgICAgICBXcml0ZS1VcGRhdGVMb2cgKCJSZXN0YXJ0IGZhaWxlZDog" +
        "IiArICRfLkV4Y2VwdGlvbi5NZXNzYWdlKQogICAgICAgIH0KICAgIH0KfQoKTmV3LUl0ZW0gLUl0ZW1UeXBlIERpcmVjdG9yeSAtRm9yY2UgLVBhdGggJFN0" +
        "YWdlRGlyIHwgT3V0LU51bGwKU2V0LUNvbnRlbnQgLUxpdGVyYWxQYXRoICRMb2dGaWxlIC1WYWx1ZSAiRnJlZUNhbSBNYW5hZ2VyIHVwZGF0ZXIgLT4gJFRh" +
        "cmdldFZlcnNpb24iIC1FbmNvZGluZyBVVEY4CldyaXRlLVN0YXR1cyAnc3RhcnRpbmcnICdXYWl0aW5nIGZvciBwcmV2aW91cyBNYW5hZ2VyIGluc3RhbmNl" +
        "IHRvIGV4aXQnCgp0cnkgewogICAgaWYgKCRPbGRQaWQgLWd0IDApIHsKICAgICAgICAkb2xkID0gR2V0LVByb2Nlc3MgLUlkICRPbGRQaWQgLUVycm9yQWN0" +
        "aW9uIFNpbGVudGx5Q29udGludWUKICAgICAgICBpZiAoJG9sZCkgewogICAgICAgICAgICBXcml0ZS1VcGRhdGVMb2cgIldhaXRpbmcgZm9yIG9sZCBNYW5h" +
        "Z2VyIFBJRCAkT2xkUGlkIgogICAgICAgICAgICB0cnkgeyBXYWl0LVByb2Nlc3MgLUlkICRPbGRQaWQgLVRpbWVvdXQgMzAgLUVycm9yQWN0aW9uIFN0b3Ag" +
        "fSBjYXRjaCB7CiAgICAgICAgICAgICAgICB0aHJvdyAiUHJldmlvdXMgTWFuYWdlciBpbnN0YW5jZSBkaWQgbm90IGV4aXQgd2l0aGluIDMwIHNlY29uZHM7" +
        "IHVwZGF0ZSBjYW5jZWxsZWQiCiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9CgogICAgaWYgKC1ub3QgKFRlc3QtUGF0aCAtTGl0ZXJhbFBhdGggJEJ1" +
        "aWxkU2NyaXB0KSkgeyB0aHJvdyAiQnVpbGQgc2NyaXB0IG5vdCBmb3VuZDogJEJ1aWxkU2NyaXB0IiB9CiAgICBSZW1vdmUtSXRlbSAtUmVjdXJzZSAtRm9y" +
        "Y2UgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgJEJ1aWxkT3V0CiAgICBXcml0ZS1TdGF0dXMgJ2J1aWxkaW5nJyAnQnVpbGRpbmcgbmV3IE1hbmFn" +
        "ZXIgdmVyc2lvbiBsb2NhbGx5JwogICAgV3JpdGUtVXBkYXRlTG9nICJCdWlsZGluZyBzdGFnZWQgc291cmNlOiAkU3RhZ2VkU291cmNlUm9vdCIKCiAgICAm" +
        "IHBvd2Vyc2hlbGwuZXhlIC1Ob1Byb2ZpbGUgLUV4ZWN1dGlvblBvbGljeSBCeXBhc3MgLUZpbGUgJEJ1aWxkU2NyaXB0IC1PdXREaXIgJEJ1aWxkT3V0IC1O" +
        "b0xhdW5jaAogICAgJGJ1aWxkRXhpdCA9ICRMQVNURVhJVENPREUKICAgIFdyaXRlLVVwZGF0ZUxvZyAiQnVpbGQgZXhpdCBjb2RlOiAkYnVpbGRFeGl0Igog" +
        "ICAgaWYgKCRidWlsZEV4aXQgLW5lIDApIHsgdGhyb3cgIk5ldyB2ZXJzaW9uIGJ1aWxkIGZhaWxlZDsgZXhpdCBjb2RlICRidWlsZEV4aXQiIH0KICAgIGlm" +
        "ICgtbm90IChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICROZXdFeGUpKSB7IHRocm93ICJCdWlsZCBjb21wbGV0ZWQgYnV0IG91dHB1dCBleGVjdXRhYmxlIHdh" +
        "cyBub3QgZm91bmQ6ICROZXdFeGUiIH0KCiAgICBXcml0ZS1TdGF0dXMgJ2luc3RhbGxpbmcnICdCdWlsZCBzdWNjZWVkZWQ7IHJlcGxhY2luZyBNYW5hZ2Vy" +
        "IGV4ZWN1dGFibGUnCiAgICBSZW1vdmUtSXRlbSAtRm9yY2UgLUVycm9yQWN0aW9uIFNpbGVudGx5Q29udGludWUgJFRlbXBFeGUKICAgIENvcHktSXRlbSAt" +
        "Rm9yY2UgLUxpdGVyYWxQYXRoICROZXdFeGUgLURlc3RpbmF0aW9uICRUZW1wRXhlCgogICAgUmVtb3ZlLUl0ZW0gLUZvcmNlIC1FcnJvckFjdGlvbiBTaWxl" +
        "bnRseUNvbnRpbnVlICRCYWNrdXBFeGUKICAgIGlmIChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRDdXJyZW50RXhlKSB7CiAgICAgICAgQ29weS1JdGVtIC1G" +
        "b3JjZSAtTGl0ZXJhbFBhdGggJEN1cnJlbnRFeGUgLURlc3RpbmF0aW9uICRCYWNrdXBFeGUKICAgIH0KCiAgICB0cnkgewogICAgICAgIGlmIChUZXN0LVBh" +
        "dGggLUxpdGVyYWxQYXRoICRDdXJyZW50RXhlKSB7IFJlbW92ZS1JdGVtIC1Gb3JjZSAtTGl0ZXJhbFBhdGggJEN1cnJlbnRFeGUgfQogICAgICAgIE1vdmUt" +
        "SXRlbSAtRm9yY2UgLUxpdGVyYWxQYXRoICRUZW1wRXhlIC1EZXN0aW5hdGlvbiAkQ3VycmVudEV4ZQogICAgfQogICAgY2F0Y2ggewogICAgICAgIFdyaXRl" +
        "LVVwZGF0ZUxvZyAoIlJlcGxhY2VtZW50IGZhaWxlZDogIiArICRfLkV4Y2VwdGlvbi5NZXNzYWdlKQogICAgICAgIGlmIChUZXN0LVBhdGggLUxpdGVyYWxQ" +
        "YXRoICRCYWNrdXBFeGUpIHsKICAgICAgICAgICAgQ29weS1JdGVtIC1Gb3JjZSAtTGl0ZXJhbFBhdGggJEJhY2t1cEV4ZSAtRGVzdGluYXRpb24gJEN1cnJl" +
        "bnRFeGUKICAgICAgICAgICAgV3JpdGUtVXBkYXRlTG9nICdSZXN0b3JlZCBiYWNrdXAgZXhlY3V0YWJsZS4nCiAgICAgICAgfQogICAgICAgIHRocm93CiAg" +
        "ICB9CgogICAgIyBDb25maWcgZmlsZXMgYXJlIHVzZXItbG9jYWwgbXV0YWJsZSBkYXRhLiBPbmx5IHNlZWQgbmV3IGRlZmF1bHRzIHdoZW4gYSBmaWxlIGlz" +
        "IGFic2VudC4KICAgICRCdWlsZENvbmZpZyA9IEpvaW4tUGF0aCAkQnVpbGRPdXQgJ0NvbmZpZycKICAgICRUYXJnZXRDb25maWcgPSBKb2luLVBhdGggJFRh" +
        "cmdldERpciAnQ29uZmlnJwogICAgaWYgKFRlc3QtUGF0aCAtTGl0ZXJhbFBhdGggJEJ1aWxkQ29uZmlnKSB7CiAgICAgICAgTmV3LUl0ZW0gLUl0ZW1UeXBl" +
        "IERpcmVjdG9yeSAtRm9yY2UgLVBhdGggJFRhcmdldENvbmZpZyB8IE91dC1OdWxsCiAgICAgICAgZm9yZWFjaCAoJG5hbWUgaW4gQCgnRmlsZW5hbWVUZXJt" +
        "cy5qc29uJywgJ3ZlcnNpb24uanNvbicpKSB7CiAgICAgICAgICAgICRzcmMgPSBKb2luLVBhdGggJEJ1aWxkQ29uZmlnICRuYW1lCiAgICAgICAgICAgICRk" +
        "c3QgPSBKb2luLVBhdGggJFRhcmdldENvbmZpZyAkbmFtZQogICAgICAgICAgICBpZiAoKFRlc3QtUGF0aCAtTGl0ZXJhbFBhdGggJHNyYykgLWFuZCAtbm90" +
        "IChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRkc3QpKSB7CiAgICAgICAgICAgICAgICBDb3B5LUl0ZW0gLUxpdGVyYWxQYXRoICRzcmMgLURlc3RpbmF0aW9u" +
        "ICRkc3QKICAgICAgICAgICAgICAgIFdyaXRlLVVwZGF0ZUxvZyAiU2VlZGVkIG1pc3NpbmcgQ29uZmlnLyRuYW1lIgogICAgICAgICAgICB9CiAgICAgICAg" +
        "fQogICAgfQoKICAgIFdyaXRlLVN0YXR1cyAnc3VjY2VzcycgJ1VwZGF0ZSBjb21wbGV0ZWQ7IHJlc3RhcnRpbmcgTWFuYWdlcicKICAgIFdyaXRlLVVwZGF0" +
        "ZUxvZyAiVXBkYXRlIGluc3RhbGxlZCBzdWNjZXNzZnVsbHk6ICRUYXJnZXRWZXJzaW9uIgogICAgUmVzdGFydC1NYW5hZ2VySWZSZXF1ZXN0ZWQKICAgIGV4" +
        "aXQgMAp9CmNhdGNoIHsKICAgICRtZXNzYWdlID0gJF8uRXhjZXB0aW9uLk1lc3NhZ2UKICAgIFdyaXRlLVVwZGF0ZUxvZyAoIlVQREFURV9GQUlMRUQ6ICIg" +
        "KyAkbWVzc2FnZSkKICAgIGlmICgtbm90IChUZXN0LVBhdGggLUxpdGVyYWxQYXRoICRDdXJyZW50RXhlKSAtYW5kIChUZXN0LVBhdGggLUxpdGVyYWxQYXRo" +
        "ICRCYWNrdXBFeGUpKSB7CiAgICAgICAgdHJ5IHsKICAgICAgICAgICAgQ29weS1JdGVtIC1Gb3JjZSAtTGl0ZXJhbFBhdGggJEJhY2t1cEV4ZSAtRGVzdGlu" +
        "YXRpb24gJEN1cnJlbnRFeGUKICAgICAgICAgICAgV3JpdGUtVXBkYXRlTG9nICdSZWNvdmVyZWQgb2xkIGV4ZWN1dGFibGUgZnJvbSBiYWNrdXAuJwogICAg" +
        "ICAgIH0gY2F0Y2ggewogICAgICAgICAgICBXcml0ZS1VcGRhdGVMb2cgKCJCYWNrdXAgcmVzdG9yZSBmYWlsZWQ6ICIgKyAkXy5FeGNlcHRpb24uTWVzc2Fn" +
        "ZSkKICAgICAgICB9CiAgICB9CiAgICBXcml0ZS1TdGF0dXMgJ2ZhaWxlZCcgJG1lc3NhZ2UKICAgIFJlc3RhcnQtTWFuYWdlcklmUmVxdWVzdGVkCiAgICBl" +
        "eGl0IDEKfQo=";

    public static string WriteTo(string stagingDirectory)
    {
        Directory.CreateDirectory(stagingDirectory);
        var path = Path.Combine(stagingDirectory, "Apply_Manager_Update_Bridge.ps1");
        var bytes = Convert.FromBase64String(PayloadBase64);
        File.WriteAllBytes(path, bytes);
        return path;
    }
}
