<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>FreeCamManager.SQLiteMigration.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FreeCamManager.Core\FreeCamManager.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.31" />
  </ItemGroup>
</Project>
